name: Build & Deploy to IIS

on:
  push:
    branches: [ "main" ]   # run pipeline on pushes to main
  pull_request:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: self-hosted   # runner installed on your IIS server

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x   # change if you're using .NET 7 or 6

    - name: Restore dependencies
      run: dotnet restore Myblog.sln

    - name: Build solution
      run: dotnet build Myblog.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test Myblog.sln --no-build --verbosity normal

    - name: Publish app
      run: dotnet publish Myblog.sln -c Release -o ./publish

    - name: Deploy to IIS folder
      run: |
        echo "Deploying to IIS..."
        Remove-Item -Recurse -Force "C:\inetpub\wwwroot\Blog_pepiline" || echo "Folder not found, skipping cleanup"
        New-Item -ItemType Directory -Path "C:\inetpub\wwwroot\Blog_pepiline" -Force
        Copy-Item -Recurse -Force "./publish/*" "C:\inetpub\wwwroot\Blog_pepiline"
